# Volume weighted price average (VWAP)
Data Analysis Python Pandas Data Manipulation Normalization External Dataset

Suppose you're given the following table, showing open and close prices as well as trading volume for a particular equity.
```
    Date      Close 	Open 	Volume
2019-01-01 	0.214420 	1.808281 	759
2019-01-02 	0.338620 	0.254375 	1324
2019-01-03 	1.051536 	1.151315 	1787
2019-01-04 	0.911552 	0.455321 	2908
2019-01-05 	0.997130 	0.359723 	713
2019-01-06 	0.426184 	0.987991 	2330
2019-01-07 	0.376917 	0.307812 	2592
2019-01-08 	0.543065 	0.136257 	1265
2019-01-09 	1.678835 	0.836795 	2674
2019-01-10 	0.481132 	0.790461 	2508
2019-01-11 	0.091329 	0.910299 	806
2019-01-12 	0.308104 	0.843959 	647
2019-01-13 	0.698701 	0.947239 	2351
2019-01-14 	0.878822 	1.046117 	2840
2019-01-15 	1.159343 	0.427352 	2302
```

In Python, write code to show the 
[volume weighted average price (VWAP)](https://www.investopedia.com/terms/v/vwap.asp) 
for a rolling 2-day window. 
The VWAP is calculated as `[sum(Price * Volume) / sum(Volume)]`,
where price is average of open and close,
and sums are over the 2-day window.

In this case, your resultant table would start on 1/3/2019 and roll daily from there.

In [1]:
import pandas as pd
import numpy as np
from io import StringIO

s = """
2019-01-01     0.214420     1.808281     759
2019-01-02     0.338620     0.254375     1324
2019-01-03     1.051536     1.151315     1787
2019-01-04     0.911552     0.455321     2908
2019-01-05     0.997130     0.359723     713
2019-01-06     0.426184     0.987991     2330
2019-01-07     0.376917     0.307812     2592
2019-01-08     0.543065     0.136257     1265
2019-01-09     1.678835     0.836795     2674
2019-01-10     0.481132     0.790461     2508
2019-01-11     0.091329     0.910299     806
2019-01-12     0.308104     0.843959     647
2019-01-13     0.698701     0.947239     2351
2019-01-14     0.878822     1.046117     2840
2019-01-15     1.159343     0.427352     2302
"""
names = ['dt','close','open','volume']
df = pd.read_csv(StringIO(s), delimiter='    ', engine='python', header=None, names=names).set_index('dt')

df.head()

               close      open  volume
dt
2019-01-01  0.214420  1.808281     759
2019-01-02  0.338620  0.254375    1324
2019-01-03  1.051536  1.151315    1787
2019-01-04  0.911552  0.455321    2908
2019-01-05  0.997130  0.359723     713

In [2]:
# see also https://stackoverflow.com/a/55676042
df['price'] = (df['open'] + df['close']) / 2
df['vwap'] = (
    (
        df['price'] * df['volume'] 
        + df['price'].shift() * df['volume'].shift()
    ) 
    / (
        df['volume'] 
        + df['volume'].shift()
    )
)
df.head()

               close      open  volume     price      vwap
dt
2019-01-01  0.214420  1.808281     759  1.011351       NaN
2019-01-02  0.338620  0.254375    1324  0.296497  0.556974
2019-01-03  1.051536  1.151315    1787  1.101425  0.758859
2019-01-04  0.911552  0.455321    2908  0.683437  0.842531
2019-01-05  0.997130  0.359723     713  0.678427  0.682450